/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileRecord = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
  'uploadDate' : IDL.Int,
});
export const UserRecord = IDL.Record({
  'storageLimit' : IDL.Nat,
  'userId' : IDL.Principal,
  'isBlocked' : IDL.Bool,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'usedStorage' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'storageLimit' : IDL.Nat,
  'principal' : IDL.Principal,
  'isBlocked' : IDL.Bool,
  'createdAt' : IDL.Int,
  'usedStorage' : IDL.Nat,
});
export const StorageStats = IDL.Record({
  'totalFiles' : IDL.Nat,
  'totalStorageUsed' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminDeleteFile' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'deleteFile' : IDL.Func([IDL.Text], [], []),
  'getAllFiles' : IDL.Func([], [IDL.Vec(FileRecord)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFile' : IDL.Func([IDL.Text], [FileRecord], ['query']),
  'getTotalStorageStats' : IDL.Func([], [StorageStats], ['query']),
  'getUser' : IDL.Func([], [UserProfile], ['query']),
  'getUserFiles' : IDL.Func([], [IDL.Vec(FileRecord)], ['query']),
  'getUserProfile' : IDL.Func([], [UserRecord], ['query']),
  'getUserProfile_compat' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text], [UserRecord], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadFile' : IDL.Func(
      [IDL.Text, IDL.Nat, ExternalBlob, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileRecord = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
    'uploadDate' : IDL.Int,
  });
  const UserRecord = IDL.Record({
    'storageLimit' : IDL.Nat,
    'userId' : IDL.Principal,
    'isBlocked' : IDL.Bool,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'usedStorage' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'storageLimit' : IDL.Nat,
    'principal' : IDL.Principal,
    'isBlocked' : IDL.Bool,
    'createdAt' : IDL.Int,
    'usedStorage' : IDL.Nat,
  });
  const StorageStats = IDL.Record({
    'totalFiles' : IDL.Nat,
    'totalStorageUsed' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminDeleteFile' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'deleteFile' : IDL.Func([IDL.Text], [], []),
    'getAllFiles' : IDL.Func([], [IDL.Vec(FileRecord)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFile' : IDL.Func([IDL.Text], [FileRecord], ['query']),
    'getTotalStorageStats' : IDL.Func([], [StorageStats], ['query']),
    'getUser' : IDL.Func([], [UserProfile], ['query']),
    'getUserFiles' : IDL.Func([], [IDL.Vec(FileRecord)], ['query']),
    'getUserProfile' : IDL.Func([], [UserRecord], ['query']),
    'getUserProfile_compat' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text], [UserRecord], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadFile' : IDL.Func(
        [IDL.Text, IDL.Nat, ExternalBlob, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };